### ISSUE TITLE
[Ingest] Ingest hi-res MPAS meshes into $EWOK_STATIC_DATA

### ISSUE THREAD

**Issue by svahl991** [JCSDA-internal/r2d2-ingest#77]
## Ingest description

Description: Need to import the files for higher-resolution MPAS meshes into `$EWOK_STATIC_DATA`. There are already mesh directories under `${EWOK_STATIC_DATA}/skylab-6.0.0/mpas` (**note: `skylab-7.0.0`, not `skylab-6.0.0`**) for 480km and 120km meshes. Need to also add directories there for meshes for 15km, 30km, 60km, and 15-3km.

Data type (_For example, observation, forecast_): MPAS Geometry (mesh) files 

Other metadata (_For example, provider, observation type, model_):  None

## Date range

N/A. Date-independent files

## Source host and directory/bucket

Source host: AWS p-cluster

Data store directory path: `/mnt/experiments-efs/steve.vahl/skylab-v7/ingest/meshes/*`

## Target data store type (select one)

- [ ] archive
- [ ] experiments
- [ ] gfs ensemble
- [x] other 
    - Please describe: `EWOK_STATIC_DATA`

## Data store checklist

Data copied into R2D2 on:

- [x] AWS pcluster
- [x] Cheyenne -> Casper/Derecho
- [x] Discover
- [x] Orion
- [x] S3 (us-east-1)
- [x] S3 (us-east-2)
- [x] S4
- [x] NOAA Parallelworks AWS --> deferred to https://github.com/JCSDA-internal/jedi-tools/issues/325
- [x] NOAA Parallelworks Azure --> deferred to https://github.com/JCSDA-internal/jedi-tools/issues/325
- [x] NOAA Parallelworks Gcloud --> deferred to https://github.com/JCSDA-internal/jedi-tools/issues/325

## Associated pull request in [r2d2/scripts](https://github.com/JCSDA-internal/r2d2/tree/develop/scripts) (if creating new ingestion scripts)

*(This instruction will change once we create the r2d2-ingest repository.)*

**Comment by ashley314** [comment]
Files are also located here `/mnt/experiments-efs/skylab-v7/mpas-fix/meshes`. @svahl991 I noticed you have now a `15km` folder in `/mnt/experiments-efs/steve.vahl/skylab-v7/ingest/meshes`. Will 15-3km be used? Or only 15km? I ask because for the 15_3km or highres case for converting I use `x5.6488066.graph.info.part.128` and inside your 15km that file does not exist. Actually Im going to swing by your office :)

**Comment by climbfuji** [comment]
Note that these will go into `${EWOK_STATIC_DATA}/skylab-7.0.0/mpas` (not `skylab-6.0.0`). Working on this now.

**Comment by ashley314** [comment]
To follow up, we discussed that 15km is different than 15-3km. The need for 15km was brought up from someone(?) which is why it was added. @climbfuji I have included 15km in `/mnt/experiments-efs/skylab-v7/mpas-fix/meshes` along with the other resolution folders that are needed.

**Comment by svahl991** [comment]
> The need for 15km was brought up from someone(?) 

@ytremolet mentioned in a meeting on Tuesday that in the future we might want to do experiments with the MPAS 15km uniform mesh because it is the most comparable MPAS mesh to the high-res cubed-sphere we've been doing experiments with. So I don't think we need it in the short term, but I just decided to include it here so we don't need another PR if we want it in the future.

**Comment by climbfuji** [comment]
Done.
